<?php

namespace Proxies\__CG__\Fdr\AdminBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Chauffeur extends \Fdr\AdminBundle\Entity\Chauffeur implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Chauffeur' . "\0" . 'feuilleDeRoutes', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Chauffeur' . "\0" . 'indisponibilites', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Chauffeur' . "\0" . 'id', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Chauffeur' . "\0" . 'nom', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Chauffeur' . "\0" . 'prenom', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Chauffeur' . "\0" . 'tel', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Chauffeur' . "\0" . 'cin', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Chauffeur' . "\0" . 'adresse', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Chauffeur' . "\0" . 'dateembauche', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Chauffeur' . "\0" . 'disponibilite', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Chauffeur' . "\0" . 'typeconvention', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Chauffeur' . "\0" . 'champssupp1', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Chauffeur' . "\0" . 'etatContrat');
        }

        return array('__isInitialized__', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Chauffeur' . "\0" . 'feuilleDeRoutes', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Chauffeur' . "\0" . 'indisponibilites', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Chauffeur' . "\0" . 'id', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Chauffeur' . "\0" . 'nom', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Chauffeur' . "\0" . 'prenom', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Chauffeur' . "\0" . 'tel', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Chauffeur' . "\0" . 'cin', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Chauffeur' . "\0" . 'adresse', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Chauffeur' . "\0" . 'dateembauche', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Chauffeur' . "\0" . 'disponibilite', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Chauffeur' . "\0" . 'typeconvention', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Chauffeur' . "\0" . 'champssupp1', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Chauffeur' . "\0" . 'etatContrat');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Chauffeur $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', array($nom));

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', array());

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom($prenom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', array($prenom));

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', array());

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setTel($tel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTel', array($tel));

        return parent::setTel($tel);
    }

    /**
     * {@inheritDoc}
     */
    public function getTel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTel', array());

        return parent::getTel();
    }

    /**
     * {@inheritDoc}
     */
    public function setCin($cin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCin', array($cin));

        return parent::setCin($cin);
    }

    /**
     * {@inheritDoc}
     */
    public function getCin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCin', array());

        return parent::getCin();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse($adresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', array($adresse));

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', array());

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateembauche($dateembauche)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateembauche', array($dateembauche));

        return parent::setDateembauche($dateembauche);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateembauche()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateembauche', array());

        return parent::getDateembauche();
    }

    /**
     * {@inheritDoc}
     */
    public function setDisponibilite($disponibilite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDisponibilite', array($disponibilite));

        return parent::setDisponibilite($disponibilite);
    }

    /**
     * {@inheritDoc}
     */
    public function getDisponibilite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisponibilite', array());

        return parent::getDisponibilite();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeconvention($typeconvention)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeconvention', array($typeconvention));

        return parent::setTypeconvention($typeconvention);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeconvention()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeconvention', array());

        return parent::getTypeconvention();
    }

    /**
     * {@inheritDoc}
     */
    public function setChampssupp1($champssupp1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChampssupp1', array($champssupp1));

        return parent::setChampssupp1($champssupp1);
    }

    /**
     * {@inheritDoc}
     */
    public function getChampssupp1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChampssupp1', array());

        return parent::getChampssupp1();
    }

    /**
     * {@inheritDoc}
     */
    public function addIndisponibilite(\Fdr\AdminBundle\Entity\Indisponibilite $indisponibilites)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addIndisponibilite', array($indisponibilites));

        return parent::addIndisponibilite($indisponibilites);
    }

    /**
     * {@inheritDoc}
     */
    public function removeIndisponibilite(\Fdr\AdminBundle\Entity\Indisponibilite $indisponibilites)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeIndisponibilite', array($indisponibilites));

        return parent::removeIndisponibilite($indisponibilites);
    }

    /**
     * {@inheritDoc}
     */
    public function getIndisponibilites()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIndisponibilites', array());

        return parent::getIndisponibilites();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtatContrat($etatContrat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtatContrat', array($etatContrat));

        return parent::setEtatContrat($etatContrat);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtatContrat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtatContrat', array());

        return parent::getEtatContrat();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function addFeuilleDeRoute(\Fdr\AdminBundle\Entity\FeuilleDeRoute $feuilleDeRoutes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addFeuilleDeRoute', array($feuilleDeRoutes));

        return parent::addFeuilleDeRoute($feuilleDeRoutes);
    }

    /**
     * {@inheritDoc}
     */
    public function removeFeuilleDeRoute(\Fdr\AdminBundle\Entity\FeuilleDeRoute $feuilleDeRoutes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeFeuilleDeRoute', array($feuilleDeRoutes));

        return parent::removeFeuilleDeRoute($feuilleDeRoutes);
    }

    /**
     * {@inheritDoc}
     */
    public function getFeuilleDeRoutes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFeuilleDeRoutes', array());

        return parent::getFeuilleDeRoutes();
    }

}
