<?php

namespace Fdr\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BonCarburantHuileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BonCarburantHuileRepository extends EntityRepository
{
}
