<?php

namespace Fdr\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Fdr\AdminBundle\Entity\Client;
use Doctrine\ORM\QueryBuilder;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends EntityRepository
{
    public function clientRamassage()
    {
       // $name='Ahmed';
         $qb = $this->createQueryBuilder('c');
         $qb ->where('c.id = :id')
             ->setParameter('id', 1);
         $cl =new Client();
         $cl=$qb ->getQuery()
                 ->getResult();

        return $cl;
    }
}
