<?php

namespace Fdr\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FeuilleDeRouteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeuilleDeRouteRepository extends EntityRepository
{
    public function clientsRamassage()
        {
            
        }
}
