feuillederoute:
    path:     /
    defaults: { _controller: "FdrAdminBundle:FeuilleDeRoute:index" }

feuillederoute_show:
    path:     /{id}/show
    defaults: { _controller: "FdrAdminBundle:FeuilleDeRoute:show" }

feuillederoute_new:
    path:     /new
    defaults: { _controller: "FdrAdminBundle:FeuilleDeRoute:new" }

feuillederoute_create:
    path:     /create
    defaults: { _controller: "FdrAdminBundle:FeuilleDeRoute:create" }
    methods:  POST

feuillederoute_edit:
    path:     /{id}/edit
    defaults: { _controller: "FdrAdminBundle:FeuilleDeRoute:edit" }

feuillederoute_update:
    path:     /{id}/update
    defaults: { _controller: "FdrAdminBundle:FeuilleDeRoute:update" }
    methods:  [POST, PUT]

feuillederoute_delete:
    path:     /{id}/delete
    defaults: { _controller: "FdrAdminBundle:FeuilleDeRoute:delete" }
    methods:  [POST, DELETE]
