missionaffretement:
    path:     /
    defaults: { _controller: "FdrAdminBundle:MissionAffretement:index" }

missionaffretement_show:
    path:     /{id}/show
    defaults: { _controller: "FdrAdminBundle:MissionAffretement:show" }

missionaffretement_new:
    path:     /new
    defaults: { _controller: "FdrAdminBundle:MissionAffretement:new" }

missionaffretement_create:
    path:     /create
    defaults: { _controller: "FdrAdminBundle:MissionAffretement:create" }
    methods:  POST

missionaffretement_edit:
    path:     /{id}/edit
    defaults: { _controller: "FdrAdminBundle:MissionAffretement:edit" }

missionaffretement_update:
    path:     /{id}/update
    defaults: { _controller: "FdrAdminBundle:MissionAffretement:update" }
    methods:  [POST, PUT]

missionaffretement_delete:
    path:     /{id}/delete
    defaults: { _controller: "FdrAdminBundle:MissionAffretement:delete" }
    methods:  [POST, DELETE]
