prestation:
    path:     /
    defaults: { _controller: "FdrAdminBundle:Prestation:index" }

prestation_show:
    path:     /{id}/show
    defaults: { _controller: "FdrAdminBundle:Prestation:show" }

prestation_new:
    path:     /new
    defaults: { _controller: "FdrAdminBundle:Prestation:new" }

prestation_create:
    path:     /create
    defaults: { _controller: "FdrAdminBundle:Prestation:create" }
    methods:  POST

prestation_edit:
    path:     /{id}/edit
    defaults: { _controller: "FdrAdminBundle:Prestation:edit" }

prestation_update:
    path:     /{id}/update
    defaults: { _controller: "FdrAdminBundle:Prestation:update" }
    methods:  [POST, PUT]

prestation_delete:
    path:     /{id}/delete
    defaults: { _controller: "FdrAdminBundle:Prestation:delete" }
    methods:  [POST, DELETE]
