vehicule:
    path:     /
    defaults: { _controller: "FdrAdminBundle:Vehicule:index" }

vehicule_show:
    path:     /{id}/show
    defaults: { _controller: "FdrAdminBundle:Vehicule:show" }

vehicule_new:
    path:     /new
    defaults: { _controller: "FdrAdminBundle:Vehicule:new" }

vehicule_create:
    path:     /create
    defaults: { _controller: "FdrAdminBundle:Vehicule:create" }
    methods:  POST

vehicule_edit:
    path:     /{id}/edit
    defaults: { _controller: "FdrAdminBundle:Vehicule:edit" }

vehicule_update:
    path:     /{id}/update
    defaults: { _controller: "FdrAdminBundle:Vehicule:update" }
    methods:  [POST, PUT]

vehicule_delete:
    path:     /{id}/delete
    defaults: { _controller: "FdrAdminBundle:Vehicule:delete" }
    methods:  [POST, DELETE]
