<?php

namespace Proxies\__CG__\Fdr\AdminBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Client extends \Fdr\AdminBundle\Entity\Client implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Client' . "\0" . 'clientFdrVs', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Client' . "\0" . 'clientFdrFs', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Client' . "\0" . 'secteurs', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Client' . "\0" . 'id', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Client' . "\0" . 'nomresponsable', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Client' . "\0" . 'prenomresponsable', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Client' . "\0" . 'tel', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Client' . "\0" . 'adresse', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Client' . "\0" . 'cin', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Client' . "\0" . 'email', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Client' . "\0" . 'fax', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Client' . "\0" . 'nomentreprise', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Client' . "\0" . 'encompte', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Client' . "\0" . 'clientaffret', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Client' . "\0" . 'clientramass', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Client' . "\0" . 'numcompte', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Client' . "\0" . 'champssupp1', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Client' . "\0" . 'champssupp2');
        }

        return array('__isInitialized__', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Client' . "\0" . 'clientFdrVs', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Client' . "\0" . 'clientFdrFs', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Client' . "\0" . 'secteurs', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Client' . "\0" . 'id', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Client' . "\0" . 'nomresponsable', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Client' . "\0" . 'prenomresponsable', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Client' . "\0" . 'tel', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Client' . "\0" . 'adresse', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Client' . "\0" . 'cin', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Client' . "\0" . 'email', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Client' . "\0" . 'fax', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Client' . "\0" . 'nomentreprise', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Client' . "\0" . 'encompte', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Client' . "\0" . 'clientaffret', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Client' . "\0" . 'clientramass', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Client' . "\0" . 'numcompte', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Client' . "\0" . 'champssupp1', '' . "\0" . 'Fdr\\AdminBundle\\Entity\\Client' . "\0" . 'champssupp2');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Client $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomresponsable($nomresponsable)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomresponsable', array($nomresponsable));

        return parent::setNomresponsable($nomresponsable);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomresponsable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomresponsable', array());

        return parent::getNomresponsable();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenomresponsable($prenomresponsable)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenomresponsable', array($prenomresponsable));

        return parent::setPrenomresponsable($prenomresponsable);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenomresponsable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenomresponsable', array());

        return parent::getPrenomresponsable();
    }

    /**
     * {@inheritDoc}
     */
    public function setTel($tel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTel', array($tel));

        return parent::setTel($tel);
    }

    /**
     * {@inheritDoc}
     */
    public function getTel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTel', array());

        return parent::getTel();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse($adresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', array($adresse));

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', array());

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setCin($cin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCin', array($cin));

        return parent::setCin($cin);
    }

    /**
     * {@inheritDoc}
     */
    public function getCin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCin', array());

        return parent::getCin();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setFax($fax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFax', array($fax));

        return parent::setFax($fax);
    }

    /**
     * {@inheritDoc}
     */
    public function getFax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFax', array());

        return parent::getFax();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomentreprise($nomentreprise)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomentreprise', array($nomentreprise));

        return parent::setNomentreprise($nomentreprise);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomentreprise()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomentreprise', array());

        return parent::getNomentreprise();
    }

    /**
     * {@inheritDoc}
     */
    public function setEncompte($encompte)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEncompte', array($encompte));

        return parent::setEncompte($encompte);
    }

    /**
     * {@inheritDoc}
     */
    public function getEncompte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEncompte', array());

        return parent::getEncompte();
    }

    /**
     * {@inheritDoc}
     */
    public function setClientaffret($clientaffret)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClientaffret', array($clientaffret));

        return parent::setClientaffret($clientaffret);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientaffret()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientaffret', array());

        return parent::getClientaffret();
    }

    /**
     * {@inheritDoc}
     */
    public function setClientramass($clientramass)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClientramass', array($clientramass));

        return parent::setClientramass($clientramass);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientramass()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientramass', array());

        return parent::getClientramass();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumcompte($numcompte)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumcompte', array($numcompte));

        return parent::setNumcompte($numcompte);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumcompte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumcompte', array());

        return parent::getNumcompte();
    }

    /**
     * {@inheritDoc}
     */
    public function setChampssupp1($champssupp1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChampssupp1', array($champssupp1));

        return parent::setChampssupp1($champssupp1);
    }

    /**
     * {@inheritDoc}
     */
    public function getChampssupp1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChampssupp1', array());

        return parent::getChampssupp1();
    }

    /**
     * {@inheritDoc}
     */
    public function setChampssupp2($champssupp2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChampssupp2', array($champssupp2));

        return parent::setChampssupp2($champssupp2);
    }

    /**
     * {@inheritDoc}
     */
    public function getChampssupp2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChampssupp2', array());

        return parent::getChampssupp2();
    }

    /**
     * {@inheritDoc}
     */
    public function addSecteur(\Fdr\AdminBundle\Entity\Secteur $secteurs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSecteur', array($secteurs));

        return parent::addSecteur($secteurs);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSecteur(\Fdr\AdminBundle\Entity\Secteur $secteurs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSecteur', array($secteurs));

        return parent::removeSecteur($secteurs);
    }

    /**
     * {@inheritDoc}
     */
    public function getSecteurs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSecteurs', array());

        return parent::getSecteurs();
    }

    /**
     * {@inheritDoc}
     */
    public function addClientFdrV(\Fdr\AdminBundle\Entity\ClientFdrV $clientFdrVs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addClientFdrV', array($clientFdrVs));

        return parent::addClientFdrV($clientFdrVs);
    }

    /**
     * {@inheritDoc}
     */
    public function removeClientFdrV(\Fdr\AdminBundle\Entity\ClientFdrV $clientFdrVs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeClientFdrV', array($clientFdrVs));

        return parent::removeClientFdrV($clientFdrVs);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientFdrVs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientFdrVs', array());

        return parent::getClientFdrVs();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

}
